src/Entity/Employee.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\EmployeeRepository")
 */
class Employee
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="integer")
     */
    private $age;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getAge(): ?int
    {
        return $this->age;
    }

    public function setAge(int $age): self
    {
        $this->age = $age;

        return $this;
    }
}

src/Entity/Shop.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ShopRepository")
 */
class Shop
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $address;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $owner_name;

    /**
     * @ORM\Column(type="integer")
     */
    private $stock;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(string $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getOwnerName(): ?string
    {
        return $this->owner_name;
    }

    public function setOwnerName(string $owner_name): self
    {
        $this->owner_name = $owner_name;

        return $this;
    }

    public function getStock(): ?int
    {
        return $this->stock;
    }

    public function setStock(int $stock): self
    {
        $this->stock = $stock;

        return $this;
    }
}

src/Form/EmployeeType.php
<?php

namespace App\Form;

use App\Entity\Employee;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class EmployeeType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name')
            ->add('age')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Employee::class,
        ]);
    }
}

src/Form/ShopType.php
<?php

namespace App\Form;

use App\Entity\Shop;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ShopType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name')
            ->add('address')
            ->add('owner_name')
            ->add('stock')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Shop::class,
        ]);
    }
}

src/Controller/EmployeeController.php
<?php

namespace App\Controller;

use App\Entity\Employee;
use App\Form\EmployeeType;
use App\Repository\EmployeeRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/employee")
 */
class EmployeeController extends AbstractController
{
    /**
     * @Route("/", name="employee_index", methods="GET")
     */
    public function index(EmployeeRepository $employeeRepository): Response
    {
        return $this->render('employee/index.html.twig', ['employees' => $employeeRepository->findAll()]);
    }

    /**
     * @Route("/new", name="employee_new", methods="GET|POST")
     */
    public function new(Request $request): Response
    {
        $employee = new Employee();
        $form = $this->createForm(EmployeeType::class, $employee);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $em->persist($employee);
            $em->flush();

            return $this->redirectToRoute('employee_index');
        }

        return $this->render('employee/new.html.twig', [
            'employee' => $employee,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="employee_show", methods="GET")
     */
    public function show(Employee $employee): Response
    {
        return $this->render('employee/show.html.twig', ['employee' => $employee]);
    }

    /**
     * @Route("/{id}/edit", name="employee_edit", methods="GET|POST")
     */
    public function edit(Request $request, Employee $employee): Response
    {
        $form = $this->createForm(EmployeeType::class, $employee);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('employee_index', ['id' => $employee->getId()]);
        }

        return $this->render('employee/edit.html.twig', [
            'employee' => $employee,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="employee_delete", methods="DELETE")
     */
    public function delete(Request $request, Employee $employee): Response
    {
        if ($this->isCsrfTokenValid('delete'.$employee->getId(), $request->request->get('_token'))) {
            $em = $this->getDoctrine()->getManager();
            $em->remove($employee);
            $em->flush();
        }

        return $this->redirectToRoute('employee_index');
    }
}

src/Controller/ShopController.php
<?php

namespace App\Controller;

use App\Entity\Shop;
use App\Form\ShopType;
use App\Repository\ShopRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/shop")
 */
class ShopController extends AbstractController
{
    /**
     * @Route("/", name="shop_index", methods="GET")
     */
    public function index(ShopRepository $shopRepository): Response
    {
        return $this->render('shop/index.html.twig', ['shops' => $shopRepository->findAll()]);
    }

    /**
     * @Route("/new", name="shop_new", methods="GET|POST")
     */
    public function new(Request $request): Response
    {
        $shop = new Shop();
        $form = $this->createForm(ShopType::class, $shop);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $em->persist($shop);
            $em->flush();

            return $this->redirectToRoute('shop_index');
        }

        return $this->render('shop/new.html.twig', [
            'shop' => $shop,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="shop_show", methods="GET")
     */
    public function show(Shop $shop): Response
    {
        return $this->render('shop/show.html.twig', ['shop' => $shop]);
    }

    /**
     * @Route("/{id}/edit", name="shop_edit", methods="GET|POST")
     */
    public function edit(Request $request, Shop $shop): Response
    {
        $form = $this->createForm(ShopType::class, $shop);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('shop_index', ['id' => $shop->getId()]);
        }

        return $this->render('shop/edit.html.twig', [
            'shop' => $shop,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="shop_delete", methods="DELETE")
     */
    public function delete(Request $request, Shop $shop): Response
    {
        if ($this->isCsrfTokenValid('delete'.$shop->getId(), $request->request->get('_token'))) {
            $em = $this->getDoctrine()->getManager();
            $em->remove($shop);
            $em->flush();
        }

        return $this->redirectToRoute('shop_index');
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
        {% block stylesheets %}{% endblock %}
    </head>
    <body>
        {% block body %}{% endblock %}
        {% block javascripts %}{% endblock %}
    </body>
</html>

templates/employee/_delete_form.html.twig
<form method="post" action="{{ path('employee_delete', {'id': employee.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ employee.id) }}">
    <button class="btn">Delete</button>
</form>

templates/employee/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/employee/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Employee{% endblock %}

{% block body %}
    <h1>Edit Employee</h1>

    {{ include('employee/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('employee_index') }}">back to list</a>

    {{ include('employee/_delete_form.html.twig') }}
{% endblock %}

templates/employee/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Employee index{% endblock %}

{% block body %}
    <h1>Employee index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Age</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for employee in employees %}
            <tr>
                <td>{{ employee.id }}</td>
                <td>{{ employee.name }}</td>
                <td>{{ employee.age }}</td>
                <td>
                    <a href="{{ path('employee_show', {'id': employee.id}) }}">show</a>
                    <a href="{{ path('employee_edit', {'id': employee.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('employee_new') }}">Create new</a>
{% endblock %}

templates/employee/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Employee{% endblock %}

{% block body %}
    <h1>Create new Employee</h1>

    {{ include('employee/_form.html.twig') }}

    <a href="{{ path('employee_index') }}">back to list</a>
{% endblock %}

templates/employee/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Employee{% endblock %}

{% block body %}
    <h1>Employee</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ employee.id }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ employee.name }}</td>
            </tr>
            <tr>
                <th>Age</th>
                <td>{{ employee.age }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('employee_index') }}">back to list</a>

    <a href="{{ path('employee_edit', {'id': employee.id}) }}">edit</a>

    {{ include('employee/_delete_form.html.twig') }}
{% endblock %}

templates/shop/_delete_form.html.twig
<form method="post" action="{{ path('shop_delete', {'id': shop.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ shop.id) }}">
    <button class="btn">Delete</button>
</form>

templates/shop/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/shop/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Shop{% endblock %}

{% block body %}
    <h1>Edit Shop</h1>

    {{ include('shop/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('shop_index') }}">back to list</a>

    {{ include('shop/_delete_form.html.twig') }}
{% endblock %}

templates/shop/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Shop index{% endblock %}

{% block body %}
    <h1>Shop index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Address</th>
                <th>Owner_name</th>
                <th>Stock</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for shop in shops %}
            <tr>
                <td>{{ shop.id }}</td>
                <td>{{ shop.name }}</td>
                <td>{{ shop.address }}</td>
                <td>{{ shop.ownerName }}</td>
                <td>{{ shop.stock }}</td>
                <td>
                    <a href="{{ path('shop_show', {'id': shop.id}) }}">show</a>
                    <a href="{{ path('shop_edit', {'id': shop.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('shop_new') }}">Create new</a>
{% endblock %}

templates/shop/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Shop{% endblock %}

{% block body %}
    <h1>Create new Shop</h1>

    {{ include('shop/_form.html.twig') }}

    <a href="{{ path('shop_index') }}">back to list</a>
{% endblock %}

templates/shop/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Shop{% endblock %}

{% block body %}
    <h1>Shop</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ shop.id }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ shop.name }}</td>
            </tr>
            <tr>
                <th>Address</th>
                <td>{{ shop.address }}</td>
            </tr>
            <tr>
                <th>Owner_name</th>
                <td>{{ shop.ownerName }}</td>
            </tr>
            <tr>
                <th>Stock</th>
                <td>{{ shop.stock }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('shop_index') }}">back to list</a>

    <a href="{{ path('shop_edit', {'id': shop.id}) }}">edit</a>

    {{ include('shop/_delete_form.html.twig') }}
{% endblock %}